const { siteId, cookiePolicyId } = Iubenda;
globalThis._iub = 'undefined' !== typeof _iub ? _iub : [];
globalThis._iub.csConfiguration = {
  askConsentAtCookiePolicyUpdate: true,
  cookiePolicyInOtherWindow: true,
  floatingPreferencesButtonDisplay: 'anchored-bottom-left',
  lang: 'de',
  perPurposeConsent: true,
  siteId,
  whitelabel: false,
  cookiePolicyId,
  banner: {
    acceptButtonCaptionColor: '#FFFFFF',
    acceptButtonColor: '#0073CE',
    acceptButtonDisplay: true,
    backgroundColor: '#FFFFFF',
    backgroundOverlay: true,
    closeButtonDisplay: false,
    customizeButtonCaptionColor: '#4D4D4D',
    customizeButtonColor: '#DADADA',
    customizeButtonDisplay: true,
    explicitWithdrawal: true,
    listPurposes: true,
    position: 'bottom',
    rejectButtonCaptionColor: '#FFFFFF',
    rejectButtonColor: '#0073CE',
    rejectButtonDisplay: true,
    textColor: '#000000',
  },
};
